let timeLeft=60,timer=null,started=false,finished=false,currentStep=0,score=0,mistakes=0,actions=0,rushCount=0,selectedTime='',selectedShipping='通常配送';
const securityCode=Math.random().toString(36).slice(2,8).toUpperCase();
const $=id=>document.getElementById(id);
function log(t,c=''){const b=$('activity');if(!b)return;const d=document.createElement('div');d.className='log-item '+c;d.textContent='['+new Date().toLocaleTimeString('ja-JP')+'] '+t;b.prepend(d);}
function updateScore(){if($('score'))$('score').textContent=score;if($('liveScore'))$('liveScore').textContent=score;}
function formatTime(s){return '00:'+String(Math.max(0,s)).padStart(2,'0')}
function updateTimer(){if($('timer')){$('timer').textContent=formatTime(timeLeft);if(timeLeft<=15)$('timer').classList.add('danger')}}
function startGame(){if(started)return;started=true;timer=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft===15)showRush('残り15秒です。予約を完了してください。');if(timeLeft<=0){clearInterval(timer);finishGame('timeout')}},1000);setTimeout(scheduleRush,11000);log('予約受付を開始','good')}
function scheduleRush(){if(finished)return;setTimeout(()=>{showRush();scheduleRush()},12000+Math.random()*9000)}
function showRush(msg){if(finished)return;rushCount++;const r=$('rush');if(!r)return;$('rushText').textContent=msg||'他の利用者による予約操作が急増しています。予約枠が変動しています。';r.classList.add('show');log('現在、NEXORA X7の予約が殺到しています。','alert');let s=parseInt($('stock').textContent)||1;if(!selectedTime)s=Math.max(1,s-1);$('stock').textContent=s+'台';setTimeout(()=>r.classList.remove('show'),4500)}
function renderStep(){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===currentStep));document.querySelectorAll('.step').forEach(s=>{const n=+s.dataset.step;s.classList.toggle('active',n===currentStep);s.classList.toggle('done',n<currentStep)});if(currentStep===4)buildSummary();window.scrollTo({top:0,behavior:'smooth'})}
function nextStep(){if(finished)return;if(currentStep===0&&!check0())return;if(currentStep===1&&!document.querySelector('input[name="model"]:checked')){alert('本体モデルを選択してください。');mistakes++;updateScore();return}if(currentStep===3&&!selectedShipping){alert('配送方法を選択してください。');return}if(currentStep<4){currentStep++;score+=15;actions++;updateScore();renderStep();log('STEP '+(currentStep+1)+'へ移動')}}
function prevStep(){if(currentStep>0){currentStep--;renderStep();log('前のステップへ戻る')}}
function check0(){for(const [id,label] of [['lastName','姓'],['firstName','名'],['email','メールアドレス'],['phone','電話番号']]){if(!$(id)||!$(id).value.trim()){alert(label+'を入力してください。');mistakes++;updateScore();return false}}return true}
function buildSummary(){const m=document.querySelector('input[name="model"]:checked')?.value||'未選択';const pay=document.querySelector('input[name="payment"]:checked')?.value||'未選択';const a=[...document.querySelectorAll('.addon:checked')].map(x=>x.value);$('summary').innerHTML=[['購入者',`${$('lastName').value} ${$('firstName').value}`],['本体',m],['カラー',$('color').value],['ストレージ',$('storage').value],['周辺機器',a.length?a.join(' / '):'なし'],['配送',selectedShipping],['時間指定',$('deliveryTime').value],['支払い',pay]].map(r=>`<div class="summary-row"><div class="summary-label">${r[0]}</div><div class="summary-value">${escapeHtml(r[1])}</div></div>`).join('')}
function finalize(){if(finished)return;const ok=['agreeTerms','agreeReservation','agreeFake','agreeTime'].every(id=>$(id).checked);if(!ok){alert('すべての確認事項に同意してください。');mistakes++;updateScore();return}if(!selectedShipping){alert('配送方法を選択してください。');return}const b=$('finalButton');if(b){b.disabled=true;b.textContent='予約処理中...'}log('最終在庫を確認しています...');setTimeout(()=>finishGame('success'),800)}
function finishGame(type){if(finished)return;finished=true;clearInterval(timer);score+=timeLeft*3;score-=mistakes*10;if(type==='success')score+=80;if(type==='timeout')score-=100;score=Math.max(0,Math.round(score));updateScore();showResult(type)}
function showResult(type){const m=document.querySelector('input[name="model"]:checked')?.value||'未選択';const pay=document.querySelector('input[name="payment"]:checked')?.value||'未選択';const order=type==='success'?'NX7-'+Math.floor(100000+Math.random()*900000):'発行なし';$('resultIcon').className='result-icon '+(type==='success'?'ok':'ng');$('resultIcon').textContent=type==='success'?'✓':'×';$('resultTitle').textContent=type==='success'?'予約が完了しました':type==='timeout'?'時間切れ':'予約未完了';$('resultMessage').textContent=type==='success'?'NEXORA X7の予約枠を確保しました。':type==='timeout'?'制限時間内に予約を完了できませんでした。':'予約処理を完了できませんでした。';$('finalScore').textContent=score;$('resultTable').innerHTML=[['結果',type==='success'?'予約確定':type==='timeout'?'時間切れ':'予約未完了'],['予約番号',order],['商品',m],['カラー',$('color').value],['ストレージ',$('storage').value],['配送',selectedShipping],['支払い方法',pay],['残り時間',formatTime(timeLeft)],['操作回数',actions],['ミス回数',mistakes],['予約殺到',rushCount+'回'],['最終スコア',score+'点']].map(r=>`<div class="result-row"><span>${escapeHtml(r[0])}</span><span>${escapeHtml(String(r[1]))}</span></div>`).join('');$('resultModal').classList.add('show')}
function escapeHtml(t){return String(t).replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[s]))}
function initReserve(){if($('securityCode'))$('securityCode').textContent=securityCode;updateTimer();updateScore();document.querySelectorAll('.option input').forEach(i=>i.addEventListener('change',()=>{document.querySelectorAll(`input[name="${i.name}"]`).forEach(x=>x.closest('.option')?.classList.remove('selected'));i.closest('.option')?.classList.add('selected');score+=3;actions++;updateScore()}));document.querySelectorAll('.addon').forEach(i=>i.addEventListener('change',()=>{i.closest('.option')?.classList.toggle('selected',i.checked);score+=3;actions++;updateScore()}));document.querySelectorAll('.shipping-card').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.shipping-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');selectedShipping=c.dataset.shipping;score+=5;actions++;updateScore()}));document.querySelectorAll('select,input[type="text"],input[type="email"],input[type="tel"]').forEach(x=>x.addEventListener('change',()=>{if(finished)return;actions++;score+=1;updateScore()}));}
window.addEventListener('load',initReserve);
